# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tasks.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

con = sqlite3.connect('Tasks.db')
cur = con.cursor()

# Create or Connect to DataBase
try:
    cur.execute('''CREATE TABLE TaskToDo (TaskText TEXT NOT NULL UNIQUE)''')
    con.commit()
    cur.execute('''CREATE TABLE TaskDone (TaskText TEXT UNIQUE)''')
    con.commit()
    print('[+] Data Base Created')
except:
    print('[+] Connection to Data Base Done')



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(854, 830)
        MainWindow.setStyleSheet("background-color: #4B5874")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Downloads/task.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 110, 831, 321))
        self.listWidget.setObjectName("listWidget")
        
        self.listWidget.setStyleSheet("background-color: #6D7C92")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 70, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Lohit Bengali")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.AddButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddButton.setGeometry(QtCore.QRect(10, 20, 131, 31))
        self.AddButton.setObjectName("AddButton")
        self.AddMoreButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddMoreButton.setGeometry(QtCore.QRect(160, 20, 131, 31))
        self.AddMoreButton.setObjectName("AddMoreButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(310, 20, 531, 31))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 450, 201, 31))
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(10, 480, 831, 321))
        self.listWidget_2.setObjectName("listWidget_2")

        self.listWidget_2.setStyleSheet("background-color: #6D7C92")
        font.setPointSize(14)
        self.listWidget.setFont(font)
        self.listWidget_2.setFont(font)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.AddCheckers()
        self.AddDones()

        self.AddButton.clicked.connect(self.GetText)
        self.listWidget.itemClicked.connect(self.Checked)

    def AddDones(self):
        Todos = cur.execute('''SELECT * FROM TaskDone''')
        for i in Todos:
            self.listWidget_2.addItem(i[0])

    def AddCheckers(self):
        self.X = []
        self.Count = 0
        Todos = cur.execute('''SELECT * FROM TaskToDo''')
        for i in Todos:
            self.X.append(QtWidgets.QListWidgetItem(i[0]))
            self.X[self.Count].setFlags(QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
            self.X[self.Count].setCheckState(QtCore.Qt.Unchecked)
            #self.X[i].stateChanged.connect(self.Checked)
            self.listWidget.addItem(self.X[self.Count])
            self.Count += 1

    def AddValueCheckers(self, text):
        self.X.append(QtWidgets.QListWidgetItem(text))
        self.X[self.Count].setFlags(QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        self.X[self.Count].setCheckState(QtCore.Qt.Unchecked)
        #self.X[i].stateChanged.connect(self.Checked)
        self.listWidget.addItem(self.X[self.Count])
        self.Count += 1

    def GetText(self):
        TaskAdd = self.textEdit.toPlainText()
        if TaskAdd != '':
            try:
                cur.execute('''INSERT INTO TaskToDo VALUES(?)''', [TaskAdd])
                con.commit()
            except:
                print('')
            self.AddValueCheckers(TaskAdd)

        
    def Checked(self, item):
        if item.checkState() == 2:
            self.listWidget_2.addItem(item.text())
            Count_SQL = 0
            Todos = cur.execute('''SELECT * FROM TaskToDo''')
            for i in Todos:
                if i[0] == item.text():
                    try:
                        cur.execute('''INSERT INTO TaskDone VALUES(?)''', [item.text()])
                        con.commit()
                        cur.execute('''DELETE FROM TaskToDo WHERE TaskText = ?''', [item.text()])
                        con.commit()
                        self.listWidget.takeItem(Count_SQL)
                    except:
                        self.listWidget.takeItem(Count_SQL)
                        cur.execute('''DELETE FROM TaskToDo WHERE TaskText = ?''', [item.text()])
                        con.commit()
                Count_SQL += 1


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Task List"))
        self.AddButton.setText(_translate("MainWindow", "Add"))
        self.AddMoreButton.setText(_translate("MainWindow", "Add with Steps"))
        self.label_2.setText(_translate("MainWindow", "Task\'s Completed"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
