# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tasks.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(854, 830)
        MainWindow.setStyleSheet("background-color: #4B5874")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Downloads/task.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 110, 831, 321))
        self.listWidget.setObjectName("listWidget")
        
        self.listWidget.setStyleSheet("background-color: #6D7C92")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 70, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Lohit Bengali")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.AddButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddButton.setGeometry(QtCore.QRect(10, 20, 131, 31))
        self.AddButton.setObjectName("AddButton")
        self.AddMoreButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddMoreButton.setGeometry(QtCore.QRect(160, 20, 131, 31))
        self.AddMoreButton.setObjectName("AddMoreButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(310, 20, 531, 31))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 450, 201, 31))
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(10, 480, 831, 321))
        self.listWidget_2.setObjectName("listWidget_2")

        self.listWidget_2.setStyleSheet("background-color: #6D7C92")
        font = QtGui.QFont()
        font.setFamily("Lohit Bengali")
        font.setPointSize(14)
        self.listWidget.setFont(font)
        self.listWidget_2.setFont(font)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.X = []
        for i in range(100):
            self.X.append(QtWidgets.QListWidgetItem(str(i)+" TEST"))
            self.X[i].setFlags(QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
            self.X[i].setCheckState(QtCore.Qt.Unchecked)
            #self.X[i].stateChanged.connect(self.Checked)
            self.listWidget.addItem(self.X[i])

        
        self.listWidget.itemClicked.connect(self.Checked)

        
    def Checked(self, item):
        print(item.currentItem())
        if item.checkState() == 2:
            self.listWidget_2.addItem(item.text())


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Task List"))
        self.AddButton.setText(_translate("MainWindow", "Add"))
        self.AddMoreButton.setText(_translate("MainWindow", "Add it Steps"))
        self.label_2.setText(_translate("MainWindow", "Task\'s Completed"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
